name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # dépendances de test si besoin
          pip install pytest

      - name: Smoke tests
        env:
          API_URL: http://localhost:5001
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests
          pytest -q tests/smoke_test.py  

      - name: Build Docker image
        run: |
          docker build -t local/mlops-dev-docker:ci .
